/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FinalComp: typeof import('./src/components/FinalComp/FinalComp.vue')['default']
    ImageComp: typeof import('./src/components/ImageComp/ImageComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextComp: typeof import('./src/components/TextComp/TextComp.vue')['default']
  }
}
